### ISSUE TITLE
上传文件如何做

### ISSUE THREAD

**Issue by leielyq** [woodemi/aliyun-oss-flutter-sdk#31]
已加群

**Comment by leielyq** [comment]
OSSCallbackRequest  这个是干嘛的呀

**Comment by leielyq** [comment]
OSSCallbackRequest  url  这个参数？  难道是把返回体转成我想要的格式？

**Comment by Sunbreak** [comment]
> OSSCallbackRequest url 这个参数？ 难道是把返回体转成我想要的格式？

建议先跑下https://github.com/aliyun/aliyun-oss-android-sdk ，基本参考这个写的

**Comment by leielyq** [comment]
ok
